services:
  - type: web
    name: eldercare-assistant
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y $(cat aptfile)
      pip install -r requirements.txt
    startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
